from __future__ import annotations
"""Report printer — generates and prints business reports."""

from PySide6.QtWidgets import QWidget
from PySide6.QtPrintSupport import QPrinter, QPrintDialog
from PySide6.QtGui import QPainter, QFont, QColor, QPen, QPageSize
from PySide6.QtCore import Qt, QRectF, QPointF

from app.utils.formatters import format_currency, format_date_display
from app.utils.logger import get_logger

logger = get_logger(__name__)


def print_report(report_data: dict, parent_widget: QWidget = None):
    """Print a business report from report data."""
    from app.database.engine import get_session
    from app.repositories.settings_repo import SettingsRepository
    session = get_session()
    try:
        settings = SettingsRepository(session).get_settings()
        shop_name = settings.shop_name or "Tailor Shop"
        currency = settings.currency or "₹"
    finally:
        session.close()

    printer = QPrinter(QPrinter.PrinterMode.ScreenResolution)
    printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))

    dialog = QPrintDialog(printer, parent_widget)
    dialog.setWindowTitle("Print Report")
    if dialog.exec() != QPrintDialog.DialogCode.Accepted:
        return

    painter = QPainter()
    if not painter.begin(printer):
        logger.error("Failed to start printing")
        return

    try:
        page_rect = printer.pageRect(QPrinter.Unit.Point)
        width = page_rect.width()
        margin = 40
        content_width = width - 2 * margin
        y = margin

        title_font = QFont("Public Sans", 18, QFont.Weight.Bold)
        header_font = QFont("Public Sans", 12, QFont.Weight.Bold)
        normal_font = QFont("Public Sans", 10)
        value_font = QFont("Public Sans", 14, QFont.Weight.Bold)

        # Title
        painter.setFont(title_font)
        painter.setPen(QColor("#091426"))
        painter.drawText(QRectF(margin, y, content_width, 26),
                         Qt.AlignmentFlag.AlignCenter, f"{shop_name} — Business Report")
        y += 35

        # Period
        painter.setFont(normal_font)
        painter.setPen(QColor("#666666"))
        start = report_data.get("start_date")
        end = report_data.get("end_date")
        period = f"Period: {format_date_display(start)} — {format_date_display(end)}"
        painter.drawText(QRectF(margin, y, content_width, 16),
                         Qt.AlignmentFlag.AlignCenter, period)
        y += 30

        painter.setPen(QPen(QColor("#091426"), 2))
        painter.drawLine(QPointF(margin, y), QPointF(width - margin, y))
        y += 20

        # Metrics
        def draw_metric(label, value):
            nonlocal y
            painter.setFont(normal_font)
            painter.setPen(QColor("#666666"))
            painter.drawText(QRectF(margin, y, content_width * 0.5, 20),
                             Qt.AlignmentFlag.AlignLeft, label)
            painter.setFont(value_font)
            painter.setPen(QColor("#091426"))
            painter.drawText(QRectF(margin + content_width * 0.5, y, content_width * 0.5, 20),
                             Qt.AlignmentFlag.AlignRight, value)
            y += 28

        draw_metric("Total Sales:", format_currency(report_data.get("total_sales", 0), currency))
        draw_metric("Total Orders:", str(report_data.get("total_orders", 0)))
        draw_metric("Completed Orders:", str(report_data.get("completed_orders", 0)))

        y += 5
        painter.setPen(QPen(QColor("#cccccc"), 1))
        painter.drawLine(QPointF(margin, y), QPointF(width - margin, y))
        y += 15

        draw_metric("Total Payments Received:", format_currency(report_data.get("total_payments", 0), currency))
        draw_metric("Pending Payments:", format_currency(report_data.get("pending_payments", 0), currency))

        y += 5
        painter.setPen(QPen(QColor("#cccccc"), 1))
        painter.drawLine(QPointF(margin, y), QPointF(width - margin, y))
        y += 15

        draw_metric("Total Expenses:", format_currency(report_data.get("total_expenses", 0), currency))

        y += 5
        painter.setPen(QPen(QColor("#091426"), 2))
        painter.drawLine(QPointF(margin, y), QPointF(width - margin, y))
        y += 15

        draw_metric("ESTIMATED PROFIT:", format_currency(report_data.get("estimated_profit", 0), currency))

        # Footer
        y += 40
        painter.setFont(QFont("Public Sans", 8))
        painter.setPen(QColor("#999999"))
        painter.drawText(QRectF(margin, y, content_width, 14),
                         Qt.AlignmentFlag.AlignCenter,
                         f"Generated by {shop_name} — Tailor Shop Manager")

    finally:
        painter.end()

    logger.info("Business report printed")
